// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dewfponmggkwaipooqqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRld2Zwb25tZ2drd2FpcG9vcXFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NzMwOTAsImV4cCI6MjA3MTQ0OTA5MH0.dyF8z7uvBgbOXePj5nqa8PqaVnNcjrxMNfFlTydig-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});